sudo: required
services:
      - docker
before_install:
      - docker build -t shibudas/docker-frontend-react -f Dockerfile .
script:
      - docker run shibudas/docker-frontend-react npm run test -- --coverage
deploy:
      provider: elasticbeanstalk
      access_key_id: 
            secure: "$AWS_ACCESS_KEY"
      secret_access_key:
            secure: "$AWS_SECRET_KEY"
      region: "us-east-1"
      app: "docker-react-app"
      env: "DockerReactApp-env"
      bucket_name: "elasticbeanstalk-us-east-1-177534457134" 
      bucket_path: "docker-react-app" 
      on:
            branch: master
      
      
